### ISSUE TITLE
www.telize.com public API is permanently shut down on November 15th.

### ISSUE THREAD

**Issue by harish2704** [darul75/satelize#5]
They shut down the public API service.

**Comment by darul75** [comment]
Hi @harish2704,

First, thanks for reporting it.

They made a very impressive work so I can understand they tend to stop free api...

My alternative will use an external dependency and one of their free database, what do you think, is it acceptable ?

**Comment by harish2704** [comment]
Hi Julien,
Thank you,
its a good and acceptable solution. I thought, this project will become
absolute after their Policy change.
Thank you for good support.
I have some small doubts regarding the new updates
- what is the increase in memory footprint due to new change? is it big?
- Do we need to do any maintenance like database updation etc... ?
- Thanks

-sent from my asus

**Comment by darul75** [comment]
memory footprint will increase a lot... database is loaded in memory inside a node Buffer (37Mo) and in future maybe a cache will increase it again.

I have just made few tests today...current database embedded is "City" one from here: 

https://dev.maxmind.com/geoip/geoip2/geolite2/

So I guess it is quite different from a paid one also :)
